apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2021-04-07T12:45:28Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
    minikube.k8s.io/commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
    minikube.k8s.io/name: minikube
    minikube.k8s.io/updated_at: 2021_04_07T21_45_31_0700
    minikube.k8s.io/version: v1.18.1
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/master: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:volumes.kubernetes.io/controller-managed-attach-detach: {}
        f:labels:
          .: {}
          f:beta.kubernetes.io/arch: {}
          f:beta.kubernetes.io/os: {}
          f:kubernetes.io/arch: {}
          f:kubernetes.io/hostname: {}
          f:kubernetes.io/os: {}
      f:status:
        f:addresses:
          .: {}
          k:{"type":"Hostname"}:
            .: {}
            f:address: {}
            f:type: {}
          k:{"type":"InternalIP"}:
            .: {}
            f:address: {}
            f:type: {}
        f:allocatable:
          .: {}
          f:cpu: {}
          f:ephemeral-storage: {}
          f:hugepages-2Mi: {}
          f:memory: {}
          f:pods: {}
        f:capacity:
          .: {}
          f:cpu: {}
          f:ephemeral-storage: {}
          f:hugepages-2Mi: {}
          f:memory: {}
          f:pods: {}
        f:conditions:
          .: {}
          k:{"type":"DiskPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"MemoryPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"PIDPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:daemonEndpoints:
          f:kubeletEndpoint:
            f:Port: {}
        f:images: {}
        f:nodeInfo:
          f:architecture: {}
          f:bootID: {}
          f:containerRuntimeVersion: {}
          f:kernelVersion: {}
          f:kubeProxyVersion: {}
          f:kubeletVersion: {}
          f:machineID: {}
          f:operatingSystem: {}
          f:osImage: {}
          f:systemUUID: {}
    manager: kubelet
    operation: Update
    time: "2021-04-07T12:45:28Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubeadm.alpha.kubernetes.io/cri-socket: {}
        f:labels:
          f:node-role.kubernetes.io/master: {}
    manager: kubeadm
    operation: Update
    time: "2021-04-07T12:45:30Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:minikube.k8s.io/commit: {}
          f:minikube.k8s.io/name: {}
          f:minikube.k8s.io/updated_at: {}
          f:minikube.k8s.io/version: {}
    manager: kubectl-label
    operation: Update
    time: "2021-04-07T12:45:32Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:node.alpha.kubernetes.io/ttl: {}
      f:spec:
        f:podCIDR: {}
        f:podCIDRs:
          .: {}
          v:"10.244.0.0/24": {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-07T12:45:46Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:node-role.kubernetes.io/control-plane: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-04-07T13:12:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:taints: {}
    manager: kubectl-taint
    operation: Update
    time: "2021-04-07T13:23:08Z"
  name: minikube
  resourceVersion: "2840"
  uid: 51df5998-59b7-419f-bfa0-a49b1fe0567f
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
status:
  addresses:
  - address: 192.168.99.105
    type: InternalIP
  - address: minikube
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 2186484Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 2186484Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2021-04-07T13:33:48Z"
    lastTransitionTime: "2021-04-07T12:45:23Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2021-04-07T13:33:48Z"
    lastTransitionTime: "2021-04-07T12:45:23Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2021-04-07T13:33:48Z"
    lastTransitionTime: "2021-04-07T12:45:23Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2021-04-07T13:33:48Z"
    lastTransitionTime: "2021-04-07T12:45:42Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - k8s.gcr.io/etcd@sha256:4ad90a11b55313b182afc186b9876c8e891531b8db4c9bf1541953021618d0e2
    - k8s.gcr.io/etcd:3.4.13-0
    sizeBytes: 253392289
  - names:
    - kubernetesui/dashboard@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6
    - kubernetesui/dashboard:v2.1.0
    sizeBytes: 225733746
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:465ba895d578fbc1c6e299e45689381fd01c54400beba9e8f1d7456077411411
    - k8s.gcr.io/kube-apiserver:v1.20.2
    sizeBytes: 121669114
  - names:
    - kindest/kindnetd@sha256:fad5da51341b25f46d6782cc59c2a3b0ca5c9dc18078d2192b488823cf9a69a6
    - kindest/kindnetd:v20210220-5b7e6d01
    sizeBytes: 119832846
  - names:
    - k8s.gcr.io/kube-proxy@sha256:326fe8a4508a5db91cf234c4867eff5ba458bc4107c2a7e15c827a74faa19be9
    - k8s.gcr.io/kube-proxy:v1.20.2
    sizeBytes: 118400203
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:842a071d4ad49b0018f7f7404ac8a4ddfc2bce2ce15b3f8131d89563fda36c9b
    - k8s.gcr.io/kube-controller-manager:v1.20.2
    sizeBytes: 115852794
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:304b3d70497bd62498f19f82f9ef164d38948e5ae94966690abfe9d1858867e2
    - k8s.gcr.io/kube-scheduler:v1.20.2
    sizeBytes: 46384634
  - names:
    - k8s.gcr.io/coredns@sha256:73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c
    - k8s.gcr.io/coredns:1.7.0
    sizeBytes: 45227747
  - names:
    - kubernetesui/metrics-scraper@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf
    - kubernetesui/metrics-scraper:v1.0.4
    sizeBytes: 36937728
  - names:
    - gcr.io/k8s-minikube/storage-provisioner@sha256:06f83c679a723d938b8776510d979c69549ad7df516279981e23554b3e68572f
    - gcr.io/k8s-minikube/storage-provisioner:v4
    sizeBytes: 29683712
  - names:
    - k8s.gcr.io/pause@sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f
    - k8s.gcr.io/pause:3.2
    sizeBytes: 682696
  nodeInfo:
    architecture: amd64
    bootID: 81dd5ba6-2534-4cbd-a6e3-ee775530ffd4
    containerRuntimeVersion: docker://20.10.3
    kernelVersion: 4.19.171
    kubeProxyVersion: v1.20.2
    kubeletVersion: v1.20.2
    machineID: a950d458d28c4f06995eea3aec2eeba1
    operatingSystem: linux
    osImage: Buildroot 2020.02.10
    systemUUID: b224f436-7368-9642-b8db-5b7d1e902128
